version: "3"
services:
  app:
    container_name: "tagged"
    image: "wenke-studio/tagged:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      API_DEBUG: ${API_DEBUG:-true}
